/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aps.evm;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Start extends javax.swing.JFrame {

    
    /**
     * Creates new form Start2
     */
    public Start() {
        this.setUndecorated(true);
        initComponents();
     
    
        namelab.setBackground(new Color(208,245,245,150));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namelab = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        imgbut = new javax.swing.JButton();
        imglab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 50)); // NOI18N
        jLabel1.setText("<html>\n<body align=center>\n\n\n\nWELCOME  To  APS BIRPUR <br> ELECTIONS  (2018-19)\n\n</body>\n</html>");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 200, 670, 160);

        namelab.setBackground(new java.awt.Color(208, 245, 245));
        namelab.setFont(new java.awt.Font("Agency FB", 2, 50)); // NOI18N
        namelab.setForeground(new java.awt.Color(255, 0, 0));
        namelab.setText("<html> <body>  <span style=\"color:black\">Made   BY</span><span style=\"color:aqua\"> :-</span><br><span style=\"color:red\">HIMANSHU SAJWAN</span><span style=\"color:black\"> & </span><span style=\"color:blue\">ABHISHEK MALIYAL</span><br><span style=\"color:orange\">CLASS XII-B</span><span style=\"color:blue\">  IP TEAM</span> <span style=\"color:green\">  (2018-19)</span>.  </body) </html>");
        namelab.setOpaque(true);
        jPanel1.add(namelab);
        namelab.setBounds(20, 400, 630, 240);

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Andalus", 1, 65)); // NOI18N
        jButton1.setText("START");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(710, 520, 240, 90);

        jButton.setBackground(new java.awt.Color(255, 0, 0));
        jButton.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton.setText("X");
        jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMousePressed(evt);
            }
        });
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jButton);
        jButton.setBounds(890, 20, 100, 93);

        imgbut.setBackground(new java.awt.Color(0, 0, 204));
        imgbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/apslogo.jpg"))); // NOI18N
        imgbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgbutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgbutMouseExited(evt);
            }
        });
        imgbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgbutActionPerformed(evt);
            }
        });
        jPanel1.add(imgbut);
        imgbut.setBounds(20, 10, 110, 130);

        imglab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGO.JPG"))); // NOI18N
        jPanel1.add(imglab);
        imglab.setBounds(0, -10, 1620, 920);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1506, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseEntered

        jButton.setBackground(Color.BLUE);
        jButton.setForeground(Color.RED);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMouseEntered

    private void jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMouseExited
        jButton.setBackground(Color.RED);
        jButton.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMouseExited

    private void jButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMousePressed
        jButton.setBackground(Color.DARK_GRAY);
        jButton.setForeground(Color.black);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMousePressed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed

        // JOptionPane.showMessageDialog(this,"BY","OK",JOptionPane.PLAIN_MESSAGE);
        //System.exit(0);
        int a=JOptionPane.showConfirmDialog(this,"Sure to Leave ?","OK",JOptionPane.YES_NO_OPTION);
        if(a==0)
        { JOptionPane.showMessageDialog(this,"BYE...","OK",JOptionPane.PLAIN_MESSAGE);
            System.exit(0);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(Color.RED);
        jButton1.setForeground(Color.blue);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(Color.CYAN);
        jButton1.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
        Person hb=new Person();
        hb.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imgbutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgbutMouseExited

        imgbut.setBackground(Color.blue);

        // TODO add your handling code here:
    }//GEN-LAST:event_imgbutMouseExited

    private void imgbutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgbutMouseEntered
        imgbut.setBackground(Color.RED);

        // TODO add your handling code here:
    }//GEN-LAST:event_imgbutMouseEntered

    private void imgbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgbutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imgbut;
    private javax.swing.JLabel imglab;
    private javax.swing.JButton jButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namelab;
    // End of variables declaration//GEN-END:variables
}
