/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aps.evm;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class Thankyou extends javax.swing.JFrame {
String value,xxx,pri,vpri,tea,st,nota,thnk;
    /**
     * Creates new form Thankyou
     */
    public Thankyou() throws InterruptedException {
        this.setUndecorated(true);
        initComponents();
        
         th.setBackground(new Color(0,0,0,170));

        cri.setBackground(new Color(0,0,0,170));
         
        
        
        
         pri="principal";
        vpri="viceprinciapl";
        tea="teacher";
        st="student";
        if(value.equals(pri)){

           thnk="Principal Mam.";
           
           

        }

        else if(value.equals(vpri)){

       thnk="Vice-Principal Mam.";
           
        }

        else if(value.equals(tea)){

            thnk="Teacher.";

        }

        else if(value.equals(st)){
             thnk="Student.";
           
        }
       
        th.setText(thnk);
        
        
        
        
      
        
        
    }
     public Thankyou(String n) throws InterruptedException {
        this.setUndecorated(true);
        initComponents();
        value=n;

        
         th.setBackground(new Color(0,0,0,100));
        cri.setBackground(new Color(0,0,0,170));
        
        
          pri="principal";
        vpri="viceprinciapl";
        tea="teacher";
        st="student";
        if(value.equals(pri)){

           thnk="Principal Mam.";
           
           

        }

        else if(value.equals(vpri)){

       thnk="Vice-Principal Mam.";
           
        }

        else if(value.equals(tea)){

            thnk="Teacher.";

        }

        else if(value.equals(st)){
             thnk="Student.";
           
        }
       
        th.setText(thnk);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        th = new javax.swing.JLabel();
        stbtn = new javax.swing.JButton();
        thnks = new javax.swing.JLabel();
        imgbut = new javax.swing.JButton();
        cri = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        th.setBackground(new java.awt.Color(0, 0, 0));
        th.setFont(new java.awt.Font("Angsana New", 3, 80)); // NOI18N
        th.setForeground(new java.awt.Color(255, 153, 0));
        th.setOpaque(true);
        jPanel1.add(th);
        th.setBounds(620, 330, 510, 90);

        stbtn.setBackground(new java.awt.Color(0, 153, 51));
        stbtn.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        stbtn.setText("START AGAIN");
        stbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stbtnMouseExited(evt);
            }
        });
        stbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbtnActionPerformed(evt);
            }
        });
        jPanel1.add(stbtn);
        stbtn.setBounds(780, 640, 180, 70);

        thnks.setFont(new java.awt.Font("Agency FB", 3, 150)); // NOI18N
        thnks.setText("<html> <body align=left>  <span style=color:orange> THANK YOU FOR <br>VOTING.... </span> </body> </html>");
        jPanel1.add(thnks);
        thnks.setBounds(120, -30, 1250, 640);

        imgbut.setBackground(new java.awt.Color(0, 0, 204));
        imgbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/apslogo.jpg"))); // NOI18N
        imgbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgbutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgbutMouseExited(evt);
            }
        });
        imgbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgbutActionPerformed(evt);
            }
        });
        jPanel1.add(imgbut);
        imgbut.setBounds(20, 10, 110, 130);

        cri.setBackground(new java.awt.Color(0, 0, 0));
        cri.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        cri.setForeground(new java.awt.Color(255, 0, 0));
        cri.setText("<HTML> <BODY ALIGN = LEFT> \"ARMY PUBLIC SCHOOL, BIRPUR <BR> -TEAM-INFORMATICS PRACTICES <BR>-HIMANSHU SAJWAN <BR>-ABHISHEK MALIYAL <BR>-KUNAL GURUNG \" </BODY> </HTML>");
        cri.setOpaque(true);
        jPanel1.add(cri);
        cri.setBounds(280, 470, 390, 290);

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thankyou.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1620, 920);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbtnActionPerformed

        
        try {
            Thread.sleep(5000);
            
             this.dispose();
        Start st=new Start();
        st.setVisible(true);
            
        } catch (InterruptedException ex) {
            Logger.getLogger(Thankyou.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
       

        // TODO add your handling code here:
    }//GEN-LAST:event_stbtnActionPerformed

    private void imgbutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgbutMouseEntered
        imgbut.setBackground(Color.RED);

        // TODO add your handling code here:
    }//GEN-LAST:event_imgbutMouseEntered

    private void imgbutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgbutMouseExited

        imgbut.setBackground(Color.blue);

        // TODO add your handling code here:
    }//GEN-LAST:event_imgbutMouseExited

    private void imgbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgbutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgbutActionPerformed

    private void stbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stbtnMouseEntered

        stbtn.setBackground(Color.RED);
        stbtn.setForeground(Color.blue);


        // TODO add your handling code here:
    }//GEN-LAST:event_stbtnMouseEntered

    private void stbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stbtnMouseExited

 stbtn.setBackground(Color.green);
        stbtn.setForeground(Color.black);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_stbtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thankyou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thankyou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thankyou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thankyou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Thankyou().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Thankyou.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cri;
    private javax.swing.JButton imgbut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stbtn;
    private javax.swing.JLabel th;
    private javax.swing.JLabel thnks;
    // End of variables declaration//GEN-END:variables
}
